# Generated by Django 3.0.7 on 2021-05-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210501_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='for_kids',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
