# Generated by Django 3.0.7 on 2021-05-01 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210501_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='wishlisted',
        ),
    ]
